// ─── SCR-ADM-043: Push Notification — Mock Data ──────────────────────────────

import { subDays, subHours, addDays, addHours, subMinutes } from "date-fns";
import { PushNotificationRecord } from "./types";

// ─── Sent Notifications ──────────────────────────────────────────────────────

const SENT: PushNotificationRecord[] = [
  {
    id: "PUSH-001",
    title: "Welcome to Playzoon!",
    body: "We're excited to have you on board. Book your first facility or training session today!",
    audiences: ["Players"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 30).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 30).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
    actualRecipients: 2391,
    deliveryRate: 97,
  },
  {
    id: "PUSH-002",
    title: "Weekend Sports Festival",
    body: "Join hundreds of players at the Weekend Sports Festival. Tournaments, prizes, and fun await!",
    audiences: ["Players"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 14).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 14).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
    actualRecipients: 2388,
    deliveryRate: 97,
  },
  {
    id: "PUSH-003",
    title: "Platform Maintenance — March 5",
    body: "Scheduled maintenance on March 5, 2:00-4:00 AM GST. Bookings may be temporarily unavailable.",
    audiences: ["Players", "Facility Providers", "Training Providers", "Coaches"],
    deliveryType: "scheduled",
    scheduledAt: subDays(new Date(), 9).toISOString(),
    sentAt: subDays(new Date(), 9).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 10).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2800,
    actualRecipients: 2744,
    deliveryRate: 98,
  },
  {
    id: "PUSH-004",
    title: "Complete Your Provider Profile",
    body: "Profiles with photos and full details get 3x more bookings. Take 2 minutes to complete yours now.",
    audiences: ["Training Providers", "Coaches"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 7).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 7).toISOString(),
    createdBy: "Admin Sarah",
    estimatedRecipients: 255,
    actualRecipients: 251,
    deliveryRate: 98,
  },
  {
    id: "PUSH-005",
    title: "Exclusive Ramadan Offer",
    body: "Book any facility this Ramadan and get 30% off. Limited slots available!",
    audiences: ["Players"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 5).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 5).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
    actualRecipients: 2388,
    deliveryRate: 97,
  },
  {
    id: "PUSH-006",
    title: "New Payout Policy Effective March 1",
    body: "We've updated our payout schedule. Payments will now be processed every Monday. See details in your Wallet.",
    audiences: ["Facility Providers", "Training Providers", "Coaches"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 3).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 3).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 350,
    actualRecipients: 344,
    deliveryRate: 98,
  },
  {
    id: "PUSH-007",
    title: "Verify Your Bank Details",
    body: "Action required: please verify your bank account details in the Wallet section to avoid payout delays.",
    audiences: ["Facility Providers"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 2).toISOString(),
    status: "Sent",
    createdAt: subDays(new Date(), 2).toISOString(),
    createdBy: "Admin Sarah",
    estimatedRecipients: 95,
    actualRecipients: 93,
    deliveryRate: 98,
  },
  {
    id: "PUSH-008",
    title: "Rate Your Last Booking",
    body: "How was your experience? Leave a rating to help other players find the best facilities in your city.",
    audiences: ["Players"],
    deliveryType: "immediate",
    sentAt: subHours(new Date(), 12).toISOString(),
    status: "Sent",
    createdAt: subHours(new Date(), 12).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
    actualRecipients: 2388,
    deliveryRate: 97,
  },
];

// ─── Scheduled Notifications ─────────────────────────────────────────────────

const SCHEDULED: PushNotificationRecord[] = [
  {
    id: "PUSH-009",
    title: "Try the New Padel Courts in Dubai!",
    body: "Two brand-new padel courts just opened in Jumeirah. Book now and be among the first players!",
    audiences: ["Players"],
    deliveryType: "scheduled",
    scheduledAt: addDays(new Date(), 1).toISOString(),
    status: "Scheduled",
    createdAt: subHours(new Date(), 6).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
  },
  {
    id: "PUSH-010",
    title: "Monthly Provider Report Ready",
    body: "Your February 2026 earnings report is ready. View your performance metrics and payout summary.",
    audiences: ["Training Providers", "Facility Providers", "Coaches"],
    deliveryType: "scheduled",
    scheduledAt: addDays(new Date(), 3).toISOString(),
    status: "Scheduled",
    createdAt: subHours(new Date(), 2).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 350,
  },
  {
    id: "PUSH-011",
    title: "Early Morning Cricket League Starts Soon",
    body: "Register your team for the Early Morning Cricket League. Matches start at 6 AM every Saturday.",
    audiences: ["Players"],
    deliveryType: "scheduled",
    scheduledAt: addDays(new Date(), 5).toISOString(),
    status: "Scheduled",
    createdAt: subMinutes(new Date(), 45).toISOString(),
    createdBy: "Admin Sarah",
    estimatedRecipients: 2450,
  },
];

// ─── Failed Notifications ────────────────────────────────────────────────────

const FAILED: PushNotificationRecord[] = [
  {
    id: "PUSH-012",
    title: "Flash Sale — 50% Off All Trainings",
    body: "For the next 24 hours only, enjoy 50% off on all training sessions platform-wide.",
    audiences: ["Players"],
    deliveryType: "immediate",
    sentAt: subDays(new Date(), 1).toISOString(),
    status: "Failed",
    createdAt: subDays(new Date(), 1).toISOString(),
    createdBy: "Super Admin",
    estimatedRecipients: 2450,
    actualRecipients: 0,
    deliveryRate: 0,
  },
];

// ─── Combined export ─────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: PushNotificationRecord[] = [
  ...SENT,
  ...SCHEDULED,
  ...FAILED,
].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
