import type { SimpleMasterDataItem } from "../shared/SimpleMasterDataPage";

export const amenityMockData: SimpleMasterDataItem[] = [
  {
    id: "AMN-1001",
    name: "Parking",
    status: "active",
    createdAt: "2024-01-08",
    updatedAt: "2024-05-15",
    isAssociated: true,
    extraFields: { icon: "P" },
  },
  {
    id: "AMN-1002",
    name: "Changing Rooms",
    status: "active",
    createdAt: "2024-01-08",
    updatedAt: "2024-05-15",
    isAssociated: true,
    extraFields: { icon: "🚪" },
  },
  {
    id: "AMN-1003",
    name: "Showers",
    status: "active",
    createdAt: "2024-02-14",
    updatedAt: "2024-06-22",
    isAssociated: true,
    extraFields: { icon: "🚿" },
  },
  {
    id: "AMN-1004",
    name: "Lockers",
    status: "active",
    createdAt: "2024-02-14",
    updatedAt: "2024-06-22",
    isAssociated: false,
    extraFields: { icon: "🔒" },
  },
  {
    id: "AMN-1005",
    name: "Cafeteria",
    status: "active",
    createdAt: "2024-03-05",
    updatedAt: "2024-07-18",
    isAssociated: true,
    extraFields: { icon: "☕" },
  },
  {
    id: "AMN-1006",
    name: "WiFi",
    status: "active",
    createdAt: "2024-03-05",
    updatedAt: "2024-07-18",
    isAssociated: true,
    extraFields: { icon: "📶" },
  },
  {
    id: "AMN-1007",
    name: "First Aid",
    status: "active",
    createdAt: "2024-04-12",
    updatedAt: "2024-08-25",
    isAssociated: false,
    extraFields: { icon: "🏥" },
  },
  {
    id: "AMN-1008",
    name: "Prayer Room",
    status: "inactive",
    createdAt: "2024-04-12",
    updatedAt: "2024-08-25",
    isAssociated: false,
    extraFields: { icon: "🕌" },
  },
  {
    id: "AMN-1009",
    name: "AC",
    status: "active",
    createdAt: "2024-05-01",
    updatedAt: "2024-09-10",
    isAssociated: true,
    extraFields: { icon: "❄️" },
  },
  {
    id: "AMN-1010",
    name: "Lighting",
    status: "active",
    createdAt: "2024-05-01",
    updatedAt: "2024-09-10",
    isAssociated: true,
    extraFields: { icon: "💡" },
  },
];
