// ─── SCR-ADM-041 & SCR-ADM-042 — Mock Data ───────────────────────────────────

import {
  PromotionRecord,
  PricingCell,
  PricingAuditEntry,
  HomepageSlotConfig,
  PlacementType,
  PromotionDuration,
  PLACEMENT_TYPES,
  DURATIONS,
} from "./types";

// ─── Date helpers ────────────────────────────────────────────────────────────

function isoDate(daysFromNow: number): string {
  const d = new Date("2026-03-10T12:00:00Z");
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString();
}

function txId(n: number): string {
  return `TXN-2026-${String(n).padStart(5, "0")}`;
}

// ─── Mock Promotions (25 records) ────────────────────────────────────────────

export const MOCK_PROMOTIONS: PromotionRecord[] = [
  // ── LIVE (8) ────────────────────────────────────────────────────────────────
  {
    id: "PROMO-001",
    entityName: "King Fahd Stadium — Main Pitch",
    entityType: "Facility",
    providerName: "King Fahd Sports Complex",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Monthly",
    startDate: isoDate(-15),
    endDate: isoDate(15),
    amount: 450,
    paymentMethod: "Credit Card",
    transactionId: txId(10001),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-002",
    entityName: "Advanced Football Programme",
    entityType: "Training",
    providerName: "Al Rashid Sports Academy",
    providerType: "Training Provider",
    placement: "Homepage",
    duration: "Weekly",
    startDate: isoDate(-3),
    endDate: isoDate(4),
    amount: 120,
    paymentMethod: "Wallet",
    transactionId: txId(10002),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-003",
    entityName: "Multi-Sport Arena — Meydan",
    entityType: "Facility",
    providerName: "Dubai Sports Hub",
    providerType: "Facility Provider",
    placement: "Listing Page",
    duration: "Monthly",
    startDate: isoDate(-10),
    endDate: isoDate(20),
    amount: 300,
    paymentMethod: "Credit Card",
    transactionId: txId(10003),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-004",
    entityName: "Youth Sprint & Agility Camp",
    entityType: "Training",
    providerName: "Falcon Athletics Club",
    providerType: "Training Provider",
    placement: "Both",
    duration: "Weekly",
    startDate: isoDate(-5),
    endDate: isoDate(2),
    amount: 200,
    paymentMethod: "Apple Pay",
    transactionId: txId(10004),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-005",
    entityName: "Padel Courts — Premium",
    entityType: "Facility",
    providerName: "Al Wasl Sports Complex",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Daily",
    startDate: isoDate(0),
    endDate: isoDate(1),
    amount: 50,
    paymentMethod: "Wallet",
    transactionId: txId(10005),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-006",
    entityName: "Competitive Swimming Programme",
    entityType: "Training",
    providerName: "Gulf Sports Academy",
    providerType: "Training Provider",
    placement: "Listing Page",
    duration: "Yearly",
    startDate: isoDate(-60),
    endDate: isoDate(305),
    amount: 2400,
    paymentMethod: "Bank Transfer",
    transactionId: txId(10006),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-007",
    entityName: "Court Complex B — Aspire Zone",
    entityType: "Facility",
    providerName: "Khalifa International Complex",
    providerType: "Facility Provider",
    placement: "Both",
    duration: "Monthly",
    startDate: isoDate(-20),
    endDate: isoDate(10),
    amount: 650,
    paymentMethod: "Credit Card",
    transactionId: txId(10007),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },
  {
    id: "PROMO-008",
    entityName: "High Performance Coaching Lab",
    entityType: "Training",
    providerName: "Elite Training Institute",
    providerType: "Training Provider",
    placement: "Homepage",
    duration: "Monthly",
    startDate: isoDate(-8),
    endDate: isoDate(22),
    amount: 450,
    paymentMethod: "Wallet",
    transactionId: txId(10008),
    paymentStatus: "Success",
    promotionStatus: "Live",
  },

  // ── UPCOMING (5) ────────────────────────────────────────────────────────────
  {
    id: "PROMO-009",
    entityName: "Summer Training Blast",
    entityType: "Training",
    providerName: "Desert Sports Academy",
    providerType: "Training Provider",
    placement: "Homepage",
    duration: "Monthly",
    startDate: isoDate(5),
    endDate: isoDate(35),
    amount: 450,
    paymentMethod: "Credit Card",
    transactionId: txId(10009),
    paymentStatus: "Success",
    promotionStatus: "Upcoming",
  },
  {
    id: "PROMO-010",
    entityName: "Premium Court A — Sports City",
    entityType: "Facility",
    providerName: "Dubai Sports Club",
    providerType: "Facility Provider",
    placement: "Both",
    duration: "Weekly",
    startDate: isoDate(3),
    endDate: isoDate(10),
    amount: 200,
    paymentMethod: "Wallet",
    transactionId: txId(10010),
    paymentStatus: "Success",
    promotionStatus: "Upcoming",
  },
  {
    id: "PROMO-011",
    entityName: "World Cup Legacy Hall",
    entityType: "Facility",
    providerName: "Lusail Arena",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Yearly",
    startDate: isoDate(10),
    endDate: isoDate(375),
    amount: 3600,
    paymentMethod: "Bank Transfer",
    transactionId: txId(10011),
    paymentStatus: "Pending",
    promotionStatus: "Upcoming",
  },
  {
    id: "PROMO-012",
    entityName: "Boxing Fundamentals Programme",
    entityType: "Training",
    providerName: "Hassan Mostafa Sports",
    providerType: "Training Provider",
    placement: "Listing Page",
    duration: "Weekly",
    startDate: isoDate(7),
    endDate: isoDate(14),
    amount: 120,
    paymentMethod: "Apple Pay",
    transactionId: txId(10012),
    paymentStatus: "Success",
    promotionStatus: "Upcoming",
  },
  {
    id: "PROMO-013",
    entityName: "Football Coaching — VIP Slots",
    entityType: "Training",
    providerName: "Ahmad Al-Rashidi Coaching",
    providerType: "Training Provider",
    placement: "Both",
    duration: "Monthly",
    startDate: isoDate(14),
    endDate: isoDate(44),
    amount: 650,
    paymentMethod: "Credit Card",
    transactionId: txId(10013),
    paymentStatus: "Success",
    promotionStatus: "Upcoming",
  },

  // ── ENDED (12) ──────────────────────────────────────────────────────────────
  {
    id: "PROMO-014",
    entityName: "Winter Athletics Camp 2025",
    entityType: "Training",
    providerName: "Falcon Athletics Club",
    providerType: "Training Provider",
    placement: "Homepage",
    duration: "Monthly",
    startDate: isoDate(-60),
    endDate: isoDate(-30),
    amount: 450,
    paymentMethod: "Credit Card",
    transactionId: txId(10014),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-015",
    entityName: "New Year Court Blitz",
    entityType: "Facility",
    providerName: "Dubai Sports Hub",
    providerType: "Facility Provider",
    placement: "Listing Page",
    duration: "Weekly",
    startDate: isoDate(-45),
    endDate: isoDate(-38),
    amount: 120,
    paymentMethod: "Wallet",
    transactionId: txId(10015),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-016",
    entityName: "Boxing Bootcamp — January",
    entityType: "Training",
    providerName: "Hassan Mostafa Sports",
    providerType: "Training Provider",
    placement: "Both",
    duration: "Monthly",
    startDate: isoDate(-70),
    endDate: isoDate(-40),
    amount: 650,
    paymentMethod: "Credit Card",
    transactionId: txId(10016),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-017",
    entityName: "Swim Club — January Sprint",
    entityType: "Training",
    providerName: "Gulf Sports Academy",
    providerType: "Training Provider",
    placement: "Listing Page",
    duration: "Weekly",
    startDate: isoDate(-50),
    endDate: isoDate(-43),
    amount: 120,
    paymentMethod: "Apple Pay",
    transactionId: txId(10017),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-018",
    entityName: "Main Pitch — February Promo",
    entityType: "Facility",
    providerName: "King Fahd Sports Complex",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Monthly",
    startDate: isoDate(-45),
    endDate: isoDate(-15),
    amount: 450,
    paymentMethod: "Bank Transfer",
    transactionId: txId(10018),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-019",
    entityName: "Transform Your Fitness — Feb",
    entityType: "Training",
    providerName: "Yousef Harthi Performance",
    providerType: "Training Provider",
    placement: "Listing Page",
    duration: "Monthly",
    startDate: isoDate(-40),
    endDate: isoDate(-10),
    amount: 300,
    paymentMethod: "Credit Card",
    transactionId: txId(10019),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-020",
    entityName: "Women's Fitness Journey",
    entityType: "Training",
    providerName: "Coach Sarah Al-Ali",
    providerType: "Training Provider",
    placement: "Both",
    duration: "Weekly",
    startDate: isoDate(-21),
    endDate: isoDate(-14),
    amount: 200,
    paymentMethod: "Wallet",
    transactionId: txId(10020),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-021",
    entityName: "Outdoor Football Pitch Promo",
    entityType: "Facility",
    providerName: "Champions Sports Club",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Daily",
    startDate: isoDate(-5),
    endDate: isoDate(-4),
    amount: 50,
    paymentMethod: "Wallet",
    transactionId: txId(10021),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-022",
    entityName: "Indoor Basketball Court A",
    entityType: "Facility",
    providerName: "Champions Sports Club",
    providerType: "Facility Provider",
    placement: "Listing Page",
    duration: "Monthly",
    startDate: isoDate(-40),
    endDate: isoDate(-10),
    amount: 300,
    paymentMethod: "Credit Card",
    transactionId: txId(10022),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-023",
    entityName: "CrossFit Fundamentals",
    entityType: "Training",
    providerName: "FitZone Academy",
    providerType: "Training Provider",
    placement: "Both",
    duration: "Monthly",
    startDate: isoDate(-35),
    endDate: isoDate(-5),
    amount: 650,
    paymentMethod: "Credit Card",
    transactionId: txId(10023),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-024",
    entityName: "Padel Court 1",
    entityType: "Facility",
    providerName: "Desert Padel Club",
    providerType: "Facility Provider",
    placement: "Homepage",
    duration: "Weekly",
    startDate: isoDate(-14),
    endDate: isoDate(-7),
    amount: 120,
    paymentMethod: "Apple Pay",
    transactionId: txId(10024),
    paymentStatus: "Failed",
    promotionStatus: "Ended",
  },
  {
    id: "PROMO-025",
    entityName: "HIIT Bootcamp",
    entityType: "Training",
    providerName: "FitZone Academy",
    providerType: "Training Provider",
    placement: "Listing Page",
    duration: "Weekly",
    startDate: isoDate(-10),
    endDate: isoDate(-3),
    amount: 120,
    paymentMethod: "Wallet",
    transactionId: txId(10025),
    paymentStatus: "Success",
    promotionStatus: "Ended",
  },
];

// ─── Pricing Matrix (SCR-ADM-042) ────────────────────────────────────────────

const PRICE_MAP: Record<PlacementType, Record<PromotionDuration, number>> = {
  Homepage:       { Daily: 50, Weekly: 120, Monthly: 450, Yearly: 3600 },
  "Listing Page": { Daily: 30, Weekly: 80,  Monthly: 300, Yearly: 2400 },
  Both:           { Daily: 70, Weekly: 200, Monthly: 650, Yearly: 5200 },
};

const ACTIVE_MAP: Record<PlacementType, Record<PromotionDuration, boolean>> = {
  Homepage:       { Daily: true,  Weekly: true,  Monthly: true,  Yearly: true },
  "Listing Page": { Daily: true,  Weekly: true,  Monthly: true,  Yearly: true },
  Both:           { Daily: true,  Weekly: true,  Monthly: true,  Yearly: false },
};

export const INITIAL_PRICING_CELLS: PricingCell[] = (() => {
  const cells: PricingCell[] = [];
  for (const placement of PLACEMENT_TYPES) {
    for (const duration of DURATIONS) {
      cells.push({
        placement,
        duration,
        price: PRICE_MAP[placement][duration],
        isActive: ACTIVE_MAP[placement][duration],
      });
    }
  }
  return cells;
})();

// ─── Homepage Slot Config ────────────────────────────────────────────────────

export const INITIAL_HOMEPAGE_SLOT_CONFIG: HomepageSlotConfig = {
  maxSlots: 10,
  currentUsage: 4,  // 4 of the Live promotions are on Homepage
};

// ─── Pricing Audit Log (last 10 entries) ─────────────────────────────────────

export const PRICING_AUDIT_LOG: PricingAuditEntry[] = [
  {
    id: "pa-001",
    timestamp: isoDate(-2),
    adminName: "Super Admin",
    changeSummary: "Updated Homepage Monthly price from SAR 400.00 to SAR 450.00",
  },
  {
    id: "pa-002",
    timestamp: isoDate(-2),
    adminName: "Super Admin",
    changeSummary: "Deactivated Both Yearly pricing plan",
  },
  {
    id: "pa-003",
    timestamp: isoDate(-5),
    adminName: "Admin Sarah",
    changeSummary: "Updated Listing Page Weekly price from SAR 70.00 to SAR 80.00",
  },
  {
    id: "pa-004",
    timestamp: isoDate(-5),
    adminName: "Admin Sarah",
    changeSummary: "Updated Listing Page Monthly price from SAR 280.00 to SAR 300.00",
  },
  {
    id: "pa-005",
    timestamp: isoDate(-10),
    adminName: "Super Admin",
    changeSummary: "Increased max homepage slots from 8 to 10",
  },
  {
    id: "pa-006",
    timestamp: isoDate(-14),
    adminName: "Super Admin",
    changeSummary: "Activated Homepage Daily pricing plan at SAR 50.00",
  },
  {
    id: "pa-007",
    timestamp: isoDate(-14),
    adminName: "Super Admin",
    changeSummary: "Updated Both Monthly price from SAR 600.00 to SAR 650.00",
  },
  {
    id: "pa-008",
    timestamp: isoDate(-21),
    adminName: "Admin Sarah",
    changeSummary: "Updated Homepage Weekly price from SAR 100.00 to SAR 120.00",
  },
  {
    id: "pa-009",
    timestamp: isoDate(-30),
    adminName: "Super Admin",
    changeSummary: "Initial pricing configuration created for all placement + duration combinations",
  },
  {
    id: "pa-010",
    timestamp: isoDate(-30),
    adminName: "Super Admin",
    changeSummary: "Set max homepage promotion slots to 8",
  },
];

// Re-export for backwards compat
export { MOCK_PROMOTIONS as MOCK_CAMPAIGNS };
export { INITIAL_PRICING_CELLS as INITIAL_PRICING_TIERS };
