import type { CountryModules, AuditEntry } from "./types";

export const INITIAL_COUNTRY_MODULES: CountryModules[] = [
  {
    countryId: "c1",
    countryName: "Saudi Arabia",
    countryCode: "SA",
    player: true,
    freelancerCoach: true,
    trainingProvider: true,
    facilityProvider: true,
    tournaments: true,
  },
  {
    countryId: "c2",
    countryName: "United Arab Emirates",
    countryCode: "AE",
    player: true,
    freelancerCoach: true,
    trainingProvider: true,
    facilityProvider: true,
    tournaments: false,
  },
  {
    countryId: "c3",
    countryName: "Bahrain",
    countryCode: "BH",
    player: true,
    freelancerCoach: false,
    trainingProvider: true,
    facilityProvider: false,
    tournaments: false,
  },
  {
    countryId: "c4",
    countryName: "Qatar",
    countryCode: "QA",
    player: true,
    freelancerCoach: false,
    trainingProvider: false,
    facilityProvider: false,
    tournaments: false,
  },
  {
    countryId: "c5",
    countryName: "Kuwait",
    countryCode: "KW",
    player: false,
    freelancerCoach: false,
    trainingProvider: false,
    facilityProvider: false,
    tournaments: false,
  },
];

export const INITIAL_AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: "aud-1",
    editedBy: "Admin (Rishabh)",
    country: "Saudi Arabia",
    field: "Tournaments",
    oldValue: "Disabled",
    newValue: "Enabled",
    timestamp: "2025-01-15 09:30:00",
  },
  {
    id: "aud-2",
    editedBy: "Admin (Rishabh)",
    country: "United Arab Emirates",
    field: "Tournaments",
    oldValue: "Enabled",
    newValue: "Disabled",
    timestamp: "2025-01-14 14:22:00",
  },
  {
    id: "aud-3",
    editedBy: "Super Admin",
    country: "Bahrain",
    field: "Freelancer Coach",
    oldValue: "Enabled",
    newValue: "Disabled",
    timestamp: "2025-01-10 11:05:00",
  },
  {
    id: "aud-4",
    editedBy: "Admin (Sara)",
    country: "Qatar",
    field: "Player",
    oldValue: "Disabled",
    newValue: "Enabled",
    timestamp: "2025-01-08 16:45:00",
  },
  {
    id: "aud-5",
    editedBy: "Super Admin",
    country: "Kuwait",
    field: "Facility Provider",
    oldValue: "Enabled",
    newValue: "Disabled",
    timestamp: "2025-01-05 10:12:00",
  },
];
