// ─── Extended player types & mock data ───────────────────────

export type PlayerStatus = "Active" | "Inactive" | "Locked" | "Unlocked";
export type LockStatus  = "Locked" | "Unlocked";

export interface PlayerRow {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  gender: string;
  status: PlayerStatus;
  dependents: number;
  createdAt: Date;
  lastActiveAt: Date;
  avatarUrl?: string;
  lockedUntil?: string;
  walletBalance: number;
  isSSOUser: boolean;
  // AC-PM-021 / AC-PM-013 additions
  nationality: string;
  defaultCity: string;
  defaultCountry: string;
  savedAddressesCount: number; // total saved addresses (including default)
}

export interface AppliedFilters {
  search: string;
  statuses: PlayerStatus[];
  nationalities: string[];
  lockStatuses: LockStatus[];
  createdFrom: Date | undefined;
  createdTo: Date | undefined;
  lastActiveFrom: Date | undefined;
  lastActiveTo: Date | undefined;
  hasDependents: boolean;
}

export const EMPTY_FILTERS: AppliedFilters = {
  search: "",
  statuses: [],
  nationalities: [],
  lockStatuses: [],
  createdFrom: undefined,
  createdTo: undefined,
  lastActiveFrom: undefined,
  lastActiveTo: undefined,
  hasDependents: false,
};

export const EXPORT_FIELDS = [
  { value: "id", label: "Player ID" },
  { value: "name", label: "Full Name" },
  { value: "email", label: "Email" },
  { value: "phone", label: "Phone" },
  { value: "gender", label: "Gender" },
  { value: "nationality", label: "Nationality" },
  { value: "status", label: "Status" },
  { value: "dependents", label: "Dependents Count" },
  { value: "createdAt", label: "Created Date" },
  { value: "lastActiveAt", label: "Last Active" },
  { value: "walletBalance", label: "Wallet Balance" },
];

// ─── Helpers ─────────────────────────────────────────────────

const BASE = new Date(2026, 1, 20, 10, 0, 0);
function daysAgo(d: number, h = 0) {
  return new Date(BASE.getTime() - (d * 86400000 + h * 3600000));
}

// ─── 30 mock players ─────────────────────────────────────────

export const MOCK_PLAYERS: PlayerRow[] = [
  {
    id: "P-004582",
    firstName: "Ava",
    lastName: "Thompson",
    email: "ava.t@example.com",
    phone: "+1 415 555 0199",
    gender: "Female",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2023, 3, 12, 10, 24),
    lastActiveAt: daysAgo(0, 2),
    walletBalance: 245.0,
    isSSOUser: true,
    nationality: "American",
    defaultCity: "San Francisco",
    defaultCountry: "USA",
    savedAddressesCount: 3,
  },
  {
    id: "P-003119",
    firstName: "Dmitri",
    lastName: "Orlov",
    email: "d.orlov@example.org",
    phone: "+44 20 7946 1234",
    gender: "Male",
    status: "Locked",
    dependents: 0,
    createdAt: new Date(2022, 10, 1, 8, 5),
    lastActiveAt: daysAgo(15),
    walletBalance: 0,
    isSSOUser: false,
    lockedUntil: "2026-09-01",
    nationality: "British",
    defaultCity: "London",
    defaultCountry: "UK",
    savedAddressesCount: 1,
  },
  {
    id: "P-005210",
    firstName: "Ahmed",
    lastName: "Al-Rashid",
    email: "ahmed.rashid@playzoon.ae",
    phone: "+971 50 123 4567",
    gender: "Male",
    status: "Active",
    dependents: 3,
    createdAt: new Date(2023, 0, 15, 10, 0),
    lastActiveAt: daysAgo(0, 1),
    walletBalance: 520.0,
    isSSOUser: true,
    nationality: "Emirati",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 2,
  },
  {
    id: "P-002987",
    firstName: "Sara",
    lastName: "Mohamed",
    email: "sara.mohamed@example.com",
    phone: "+966 55 987 6543",
    gender: "Female",
    status: "Inactive",
    dependents: 0,
    createdAt: new Date(2023, 2, 22, 9, 30),
    lastActiveAt: daysAgo(45),
    walletBalance: 0,
    isSSOUser: false,
    nationality: "Saudi Arabian",
    defaultCity: "Riyadh",
    defaultCountry: "Saudi Arabia",
    savedAddressesCount: 1,
  },
  {
    id: "P-004100",
    firstName: "Khalid",
    lastName: "Ibrahim",
    email: "khalid.ibrahim@example.com",
    phone: "+966 54 555 1212",
    gender: "Male",
    status: "Locked",
    dependents: 1,
    createdAt: new Date(2023, 5, 10, 14, 15),
    lastActiveAt: daysAgo(30),
    walletBalance: 45.5,
    isSSOUser: false,
    lockedUntil: "2026-04-15",
    nationality: "Saudi Arabian",
    defaultCity: "Jeddah",
    defaultCountry: "Saudi Arabia",
    savedAddressesCount: 1,
  },
  {
    id: "P-005678",
    firstName: "Fatima",
    lastName: "Al-Saud",
    email: "fatima.alsaud@example.com",
    phone: "+966 56 111 2222",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2022, 10, 5, 8, 45),
    lastActiveAt: daysAgo(0, 5),
    walletBalance: 500.0,
    isSSOUser: true,
    nationality: "Saudi Arabian",
    defaultCity: "Riyadh",
    defaultCountry: "Saudi Arabia",
    savedAddressesCount: 2,
  },
  {
    id: "P-006001",
    firstName: "Mohammed",
    lastName: "Abdullah",
    email: "mohammed.abdullah@example.com",
    phone: "+966 59 333 4444",
    gender: "Male",
    status: "Active",
    dependents: 1,
    createdAt: new Date(2023, 1, 28, 11, 20),
    lastActiveAt: daysAgo(1),
    walletBalance: 75.25,
    isSSOUser: false,
    nationality: "Emirati",
    defaultCity: "Abu Dhabi",
    defaultCountry: "UAE",
    savedAddressesCount: 1,
  },
  {
    id: "P-006234",
    firstName: "Liam",
    lastName: "O'Brien",
    email: "liam.obrien@mail.ie",
    phone: "+353 87 123 4567",
    gender: "Male",
    status: "Active",
    dependents: 4,
    createdAt: new Date(2024, 0, 10, 9, 0),
    lastActiveAt: daysAgo(0, 3),
    walletBalance: 310.0,
    isSSOUser: false,
    nationality: "Irish",
    defaultCity: "Dublin",
    defaultCountry: "Ireland",
    savedAddressesCount: 3,
  },
  {
    id: "P-006500",
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki.t@example.jp",
    phone: "+81 90 1234 5678",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2024, 3, 5, 14, 0),
    lastActiveAt: daysAgo(2),
    walletBalance: 180.0,
    isSSOUser: true,
    nationality: "Japanese",
    defaultCity: "Tokyo",
    defaultCountry: "Japan",
    savedAddressesCount: 1,
  },
  {
    id: "P-006780",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@mail.in",
    phone: "+91 98765 43210",
    gender: "Female",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2024, 5, 20, 11, 30),
    lastActiveAt: daysAgo(0, 6),
    walletBalance: 90.0,
    isSSOUser: false,
    nationality: "Indian",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 3,
  },
  {
    id: "P-007001",
    firstName: "Carlos",
    lastName: "Garcia",
    email: "carlos.garcia@mail.es",
    phone: "+34 612 345 678",
    gender: "Male",
    status: "Inactive",
    dependents: 1,
    createdAt: new Date(2023, 7, 15, 16, 0),
    lastActiveAt: daysAgo(90),
    walletBalance: 0,
    isSSOUser: false,
    nationality: "Spanish",
    defaultCity: "Barcelona",
    defaultCountry: "Spain",
    savedAddressesCount: 1,
  },
  {
    id: "P-007200",
    firstName: "Noor",
    lastName: "Al-Mutawa",
    email: "noor.m@yahoo.com",
    phone: "+971 50 888 9999",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2024, 8, 1, 7, 45),
    lastActiveAt: daysAgo(0, 4),
    walletBalance: 150.0,
    isSSOUser: true,
    nationality: "Kuwaiti",
    defaultCity: "Kuwait City",
    defaultCountry: "Kuwait",
    savedAddressesCount: 2,
  },
  {
    id: "P-007400",
    firstName: "Emily",
    lastName: "Chen",
    email: "emily.chen@gmail.com",
    phone: "+1 650 555 7890",
    gender: "Female",
    status: "Active",
    dependents: 1,
    createdAt: new Date(2024, 1, 14, 10, 0),
    lastActiveAt: daysAgo(3),
    walletBalance: 420.0,
    isSSOUser: false,
    nationality: "American",
    defaultCity: "San Jose",
    defaultCountry: "USA",
    savedAddressesCount: 2,
  },
  {
    id: "P-007600",
    firstName: "Omar",
    lastName: "Hassan",
    email: "omar.h@outlook.com",
    phone: "+971 55 444 5566",
    gender: "Male",
    status: "Locked",
    dependents: 0,
    createdAt: new Date(2023, 9, 20, 13, 0),
    lastActiveAt: daysAgo(60),
    walletBalance: 25.0,
    isSSOUser: false,
    lockedUntil: "2026-05-01",
    nationality: "Emirati",
    defaultCity: "Sharjah",
    defaultCountry: "UAE",
    savedAddressesCount: 1,
  },
  {
    id: "P-007800",
    firstName: "Sophie",
    lastName: "Laurent",
    email: "sophie.l@mail.fr",
    phone: "+33 6 12 34 56 78",
    gender: "Female",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2024, 4, 10, 9, 30),
    lastActiveAt: daysAgo(1, 5),
    walletBalance: 200.0,
    isSSOUser: true,
    nationality: "French",
    defaultCity: "Paris",
    defaultCountry: "France",
    savedAddressesCount: 3,
  },
  {
    id: "P-008000",
    firstName: "Rashid",
    lastName: "Al-Mansoori",
    email: "rashid.m@gmail.com",
    phone: "+971 55 111 2233",
    gender: "Male",
    status: "Active",
    dependents: 3,
    createdAt: new Date(2023, 4, 1, 8, 0),
    lastActiveAt: daysAgo(0, 8),
    walletBalance: 680.0,
    isSSOUser: false,
    nationality: "Emirati",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 2,
  },
  {
    id: "P-008200",
    firstName: "Aisha",
    lastName: "Khalifa",
    email: "aisha.k@hotmail.com",
    phone: "+971 50 444 5566",
    gender: "Female",
    status: "Inactive",
    dependents: 0,
    createdAt: new Date(2024, 6, 15, 12, 0),
    lastActiveAt: daysAgo(120),
    walletBalance: 0,
    isSSOUser: false,
    nationality: "Bahraini",
    defaultCity: "Manama",
    defaultCountry: "Bahrain",
    savedAddressesCount: 1,
  },
  {
    id: "P-008400",
    firstName: "James",
    lastName: "Wilson",
    email: "james.w@company.co.uk",
    phone: "+44 77 0011 2233",
    gender: "Male",
    status: "Active",
    dependents: 1,
    createdAt: new Date(2024, 9, 3, 15, 0),
    lastActiveAt: daysAgo(0, 10),
    walletBalance: 55.0,
    isSSOUser: false,
    nationality: "British",
    defaultCity: "Manchester",
    defaultCountry: "UK",
    savedAddressesCount: 2,
  },
  {
    id: "P-008600",
    firstName: "Laila",
    lastName: "Bint Saeed",
    email: "laila.s@gmail.com",
    phone: "+971 55 222 3344",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2025, 0, 10, 10, 0),
    lastActiveAt: daysAgo(5),
    walletBalance: 320.0,
    isSSOUser: true,
    nationality: "Emirati",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 1,
  },
  {
    id: "P-008800",
    firstName: "Tariq",
    lastName: "Mansour",
    email: "tariq.m@protonmail.com",
    phone: "+971 56 777 8899",
    gender: "Male",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2024, 11, 1, 7, 0),
    lastActiveAt: daysAgo(0, 12),
    walletBalance: 140.0,
    isSSOUser: false,
    nationality: "Lebanese",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 2,
  },
  {
    id: "P-009000",
    firstName: "Maria",
    lastName: "Santos",
    email: "maria.santos@mail.br",
    phone: "+55 11 91234 5678",
    gender: "Female",
    status: "Active",
    dependents: 1,
    createdAt: new Date(2025, 1, 5, 9, 0),
    lastActiveAt: daysAgo(2, 3),
    walletBalance: 88.0,
    isSSOUser: false,
    nationality: "Brazilian",
    defaultCity: "São Paulo",
    defaultCountry: "Brazil",
    savedAddressesCount: 1,
  },
  {
    id: "P-009200",
    firstName: "Hassan",
    lastName: "Bakr",
    email: "hassan.b@facilitygroup.ae",
    phone: "+971 2 445 6789",
    gender: "Male",
    status: "Active",
    dependents: 5,
    createdAt: new Date(2023, 8, 12, 11, 0),
    lastActiveAt: daysAgo(0, 1),
    walletBalance: 1200.0,
    isSSOUser: true,
    nationality: "Egyptian",
    defaultCity: "Abu Dhabi",
    defaultCountry: "UAE",
    savedAddressesCount: 2,
  },
  {
    id: "P-009400",
    firstName: "Chen",
    lastName: "Wei",
    email: "chen.wei@mail.cn",
    phone: "+86 138 0013 8000",
    gender: "Male",
    status: "Inactive",
    dependents: 0,
    createdAt: new Date(2024, 2, 28, 16, 0),
    lastActiveAt: daysAgo(200),
    walletBalance: 0,
    isSSOUser: false,
    nationality: "Chinese",
    defaultCity: "Shanghai",
    defaultCountry: "China",
    savedAddressesCount: 1,
  },
  {
    id: "P-009600",
    firstName: "Youssef",
    lastName: "Nabil",
    email: "youssef.n@gmail.com",
    phone: "+971 50 999 0011",
    gender: "Male",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2024, 7, 20, 8, 30),
    lastActiveAt: daysAgo(1, 8),
    walletBalance: 65.0,
    isSSOUser: false,
    nationality: "Moroccan",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 1,
  },
  {
    id: "P-009800",
    firstName: "Anna",
    lastName: "Müller",
    email: "anna.m@mail.de",
    phone: "+49 170 123 4567",
    gender: "Female",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2025, 0, 20, 14, 0),
    lastActiveAt: daysAgo(0, 16),
    walletBalance: 410.0,
    isSSOUser: true,
    nationality: "German",
    defaultCity: "Berlin",
    defaultCountry: "Germany",
    savedAddressesCount: 2,
  },
  {
    id: "P-010000",
    firstName: "Ali",
    lastName: "Hassan",
    email: "ali.h@outlook.com",
    phone: "+971 55 987 6543",
    gender: "Male",
    status: "Active",
    dependents: 1,
    createdAt: new Date(2024, 10, 5, 10, 0),
    lastActiveAt: daysAgo(0, 2),
    walletBalance: 330.0,
    isSSOUser: false,
    nationality: "Jordanian",
    defaultCity: "Amman",
    defaultCountry: "Jordan",
    savedAddressesCount: 1,
  },
  {
    id: "P-010200",
    firstName: "Fatima",
    lastName: "Al-Zahra",
    email: "fatima.z@icloud.com",
    phone: "+971 56 333 2211",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2025, 1, 1, 12, 0),
    lastActiveAt: daysAgo(4),
    walletBalance: 78.0,
    isSSOUser: true,
    nationality: "Omani",
    defaultCity: "Muscat",
    defaultCountry: "Oman",
    savedAddressesCount: 1,
  },
  {
    id: "P-010400",
    firstName: "Ibrahim",
    lastName: "Al-Qadi",
    email: "ibrahim@desertpadel.com",
    phone: "+971 4 556 7788",
    gender: "Male",
    status: "Active",
    dependents: 2,
    createdAt: new Date(2024, 5, 15, 9, 0),
    lastActiveAt: daysAgo(0, 20),
    walletBalance: 190.0,
    isSSOUser: false,
    nationality: "Palestinian",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 3,
  },
  {
    id: "P-010600",
    firstName: "Coach Sara",
    lastName: "Khalil",
    email: "sara.k@coachpro.com",
    phone: "+971 56 123 4567",
    gender: "Female",
    status: "Active",
    dependents: 0,
    createdAt: new Date(2024, 8, 10, 7, 0),
    lastActiveAt: daysAgo(0, 5),
    walletBalance: 550.0,
    isSSOUser: false,
    nationality: "Lebanese",
    defaultCity: "Dubai",
    defaultCountry: "UAE",
    savedAddressesCount: 2,
  },
  {
    id: "P-010800",
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@mail.kr",
    phone: "+82 10 1234 5678",
    gender: "Male",
    status: "Locked",
    dependents: 0,
    createdAt: new Date(2024, 4, 1, 13, 0),
    lastActiveAt: daysAgo(40),
    walletBalance: 10.0,
    isSSOUser: false,
    lockedUntil: "2026-06-01",
    nationality: "South Korean",
    defaultCity: "Seoul",
    defaultCountry: "South Korea",
    savedAddressesCount: 1,
  },
];

// ─── Player audit events (scoped mock) ───────────────────────

export interface PlayerAuditEvent {
  id: string;
  timestamp: Date;
  actor: string;
  actorRole: string;
  action: "INSERT" | "UPDATE" | "DELETE";
  field: string;
  oldValue: unknown;
  newValue: unknown;
  ipAddress: string;
  module: string;
}

export function getPlayerAuditEvents(playerId: string): PlayerAuditEvent[] {
  const base = new Date(2026, 1, 18, 14, 0, 0);
  function ago(m: number) { return new Date(base.getTime() - m * 60000); }

  return [
    {
      id: `${playerId}-AE-001`,
      timestamp: ago(30),
      actor: "System",
      actorRole: "System",
      action: "UPDATE",
      field: "last_active_at",
      oldValue: "2026-02-18T13:00:00Z",
      newValue: "2026-02-18T13:30:00Z",
      ipAddress: "10.0.0.1",
      module: "auth",
    },
    {
      id: `${playerId}-AE-002`,
      timestamp: ago(120),
      actor: "Sarah Johnson",
      actorRole: "Sub-Admin",
      action: "UPDATE",
      field: "status",
      oldValue: "Inactive",
      newValue: "Active",
      ipAddress: "10.0.1.22",
      module: "admin",
    },
    {
      id: `${playerId}-AE-003`,
      timestamp: ago(300),
      actor: "Khalid Al-Rashid",
      actorRole: "Super Admin",
      action: "UPDATE",
      field: "email_verified",
      oldValue: false,
      newValue: true,
      ipAddress: "10.0.1.45",
      module: "admin",
    },
    {
      id: `${playerId}-AE-004`,
      timestamp: ago(600),
      actor: "System",
      actorRole: "System",
      action: "UPDATE",
      field: "wallet_balance",
      oldValue: 0,
      newValue: 150.00,
      ipAddress: "10.0.0.1",
      module: "payments",
    },
    {
      id: `${playerId}-AE-005`,
      timestamp: ago(1200),
      actor: "Omar Fadel",
      actorRole: "Sub-Admin",
      action: "UPDATE",
      field: "phone",
      oldValue: "+971 50 000 0000",
      newValue: "+971 50 123 4567",
      ipAddress: "10.0.1.33",
      module: "admin",
    },
    {
      id: `${playerId}-AE-006`,
      timestamp: ago(2400),
      actor: "System",
      actorRole: "System",
      action: "INSERT",
      field: "dependent",
      oldValue: null,
      newValue: { name: "Omar Jr.", relation: "Son", age: 8 },
      ipAddress: "10.0.0.1",
      module: "players",
    },
    {
      id: `${playerId}-AE-007`,
      timestamp: ago(4000),
      actor: "System",
      actorRole: "System",
      action: "INSERT",
      field: "player_account",
      oldValue: null,
      newValue: { id: playerId, status: "Active", source: "mobile_app" },
      ipAddress: "10.0.0.1",
      module: "registration",
    },
  ];
}