// ─── SCR-ADM-039 / SCR-ADM-040 — Mock Data ──────────────────────────────────

import type { SubAdmin, Role, RolePermissions } from "./types";

// ─── Mock Roles ─────────────────────────────────────────────────────────────

const contentManagerPerms: RolePermissions = {
  "cms-notifications": ["Banners", "FAQs", "Static Pages", "Manual Notifications", "View/Edit Settings"],
  "reviews-ratings": ["View", "Hide/Unhide"],
};

const financeOfficerPerms: RolePermissions = {
  "wallet-payments": ["View Wallet", "View History", "Approve/Reject Payout", "Manual Adjust"],
  "reports-analytics": ["View Dashboard", "View Reports", "Export"],
  "bank-accounts": ["View", "Approve/Reject"],
};

const supportAgentPerms: RolePermissions = {
  "user-management": ["View", "Edit"],
  "bookings-cancellations": ["View", "Cancel"],
  "contact-support": ["View", "Reply", "Resolve"],
};

const operationsManagerPerms: RolePermissions = {
  "user-management": ["View", "Edit", "Active/Inactive", "Lock/Unlock"],
  "provider-management": ["View", "Edit", "Add", "Active/Inactive", "Approve/Reject"],
  "bookings-cancellations": ["View", "Cancel"],
  "wallet-payments": ["View Wallet", "View History"],
  "reports-analytics": ["View Dashboard", "View Reports", "Export"],
};

const providerRelationsPerms: RolePermissions = {
  "provider-management": ["View", "Edit", "Add", "Active/Inactive", "Lock/Unlock", "Approve/Reject"],
  "training-facility": ["View", "Active/Inactive"],
  "request-facility": ["View", "Approve/Reject", "Remove Assigned"],
};

const reportsAnalystPerms: RolePermissions = {
  "reports-analytics": ["View Dashboard", "View Reports", "Export"],
};

const moderatorPerms: RolePermissions = {
  "reviews-ratings": ["View", "Hide/Unhide"],
  "user-management": ["View"],
  "contact-support": ["View", "Reply"],
};

const marketingPerms: RolePermissions = {
  "cms-notifications": ["Banners", "Manual Notifications"],
  "promotions-refresh": ["View", "Edit", "Add", "Delete Pricing"],
};

export const MOCK_ROLES: Role[] = [
  {
    id: "role-001",
    name: "Content Manager",
    description: "Manages CMS content, banners, FAQs, and moderates reviews.",
    colourId: "blue",
    colourHex: "#3B82F6",
    permissions: contentManagerPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-09-01T08:00:00Z",
    updatedAt: "2025-11-10T09:00:00Z",
  },
  {
    id: "role-002",
    name: "Finance Officer",
    description: "Oversees wallets, payment history, payout approvals, and financial reports.",
    colourId: "emerald",
    colourHex: "#10B981",
    permissions: financeOfficerPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-09-10T10:00:00Z",
    updatedAt: "2025-12-01T10:30:00Z",
  },
  {
    id: "role-003",
    name: "Support Agent",
    description: "Handles user queries, manages bookings, and resolves support tickets.",
    colourId: "cyan",
    colourHex: "#06B6D4",
    permissions: supportAgentPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-10-05T08:00:00Z",
    updatedAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "role-004",
    name: "Operations Manager",
    description: "Full operational oversight across users, providers, bookings, and reports.",
    colourId: "indigo",
    colourHex: "#6366F1",
    permissions: operationsManagerPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-08-15T12:00:00Z",
    updatedAt: "2026-02-10T12:00:00Z",
  },
  {
    id: "role-005",
    name: "Provider Relations",
    description: "Manages provider accounts, facility requests, and training programme approvals.",
    colourId: "orange",
    colourHex: "#F97316",
    permissions: providerRelationsPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-11-01T09:00:00Z",
    updatedAt: "2026-01-12T11:00:00Z",
  },
  {
    id: "role-006",
    name: "Reports Analyst",
    description: "Read-only access to dashboards and reports with export capability.",
    colourId: "violet",
    colourHex: "#8B5CF6",
    permissions: reportsAnalystPerms,
    status: "Active",
    subAdminCount: 1,
    createdAt: "2025-12-01T14:00:00Z",
    updatedAt: "2026-02-18T14:00:00Z",
  },
  {
    id: "role-007",
    name: "Moderator",
    description: "Monitors reviews, user reports, and handles content moderation.",
    colourId: "pink",
    colourHex: "#EC4899",
    permissions: moderatorPerms,
    status: "Inactive",
    subAdminCount: 1,
    createdAt: "2025-07-01T09:00:00Z",
    updatedAt: "2026-01-15T16:30:00Z",
  },
  {
    id: "role-008",
    name: "Marketing Coordinator",
    description: "Manages promotional content, banners, and notification campaigns.",
    colourId: "amber",
    colourHex: "#F59E0B",
    permissions: marketingPerms,
    status: "Inactive",
    subAdminCount: 1,
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2026-01-20T09:45:00Z",
  },
];

// ─── Mock Sub-Admins ────────────────────────────────────────────────────────

export const MOCK_SUB_ADMINS: SubAdmin[] = [
  {
    id: "sa-001",
    fullName: "Layla Al-Mansouri",
    email: "layla.almansouri@playzoon.com",
    mobile: "551234567",
    countryCode: "+966",
    roleId: "role-001",
    roleName: "Content Manager",
    roleColourHex: "#3B82F6",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-02-21T08:45:00Z",
    createdAt: "2025-11-10T09:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-002",
    fullName: "Omar Khalid Hassan",
    email: "omar.hassan@playzoon.com",
    mobile: "559876543",
    countryCode: "+966",
    roleId: "role-002",
    roleName: "Finance Officer",
    roleColourHex: "#10B981",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-02-20T14:22:00Z",
    createdAt: "2025-12-01T10:30:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-003",
    fullName: "Sara Youssef Nour",
    email: "sara.nour@playzoon.com",
    mobile: "501112233",
    countryCode: "+971",
    roleId: "role-003",
    roleName: "Support Agent",
    roleColourHex: "#06B6D4",
    nationality: "Egyptian",
    country: "United Arab Emirates",
    status: "Active",
    lastLogin: "2026-02-19T11:05:00Z",
    createdAt: "2026-01-05T08:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-004",
    fullName: "Faisal Al-Otaibi",
    email: "faisal.otaibi@playzoon.com",
    mobile: "557771234",
    countryCode: "+966",
    roleId: "role-005",
    roleName: "Provider Relations",
    roleColourHex: "#F97316",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-02-18T09:33:00Z",
    createdAt: "2026-01-12T11:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-005",
    fullName: "Nadia Ramzi Haddad",
    email: "nadia.haddad@playzoon.com",
    mobile: "508889999",
    countryCode: "+962",
    roleId: "role-004",
    roleName: "Operations Manager",
    roleColourHex: "#6366F1",
    nationality: "Jordanian",
    country: "Jordan",
    status: "Active",
    lastLogin: "2026-02-21T07:10:00Z",
    createdAt: "2025-10-20T12:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-006",
    fullName: "Tariq Mohammed Al-Ghamdi",
    email: "tariq.ghamdi@playzoon.com",
    mobile: "554443322",
    countryCode: "+966",
    roleId: "role-004",
    roleName: "Operations Manager",
    roleColourHex: "#6366F1",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-02-20T16:55:00Z",
    createdAt: "2025-09-15T08:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-007",
    fullName: "Reem Al-Zahrawi",
    email: "reem.zahrawi@playzoon.com",
    mobile: "506667788",
    countryCode: "+966",
    roleId: "role-006",
    roleName: "Reports Analyst",
    roleColourHex: "#8B5CF6",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-03-01T10:12:00Z",
    createdAt: "2026-02-18T14:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-008",
    fullName: "Khalid Bin Saleh",
    email: "khalid.saleh@playzoon.com",
    mobile: "551110000",
    countryCode: "+966",
    roleId: "role-007",
    roleName: "Moderator",
    roleColourHex: "#EC4899",
    nationality: "Bahraini",
    country: "Bahrain",
    status: "Inactive",
    lastLogin: "2026-01-10T10:00:00Z",
    createdAt: "2025-08-01T09:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-009",
    fullName: "Amira Farouk Ibrahim",
    email: "amira.ibrahim@playzoon.com",
    mobile: "201234567",
    countryCode: "+20",
    roleId: "role-008",
    roleName: "Marketing Coordinator",
    roleColourHex: "#F59E0B",
    nationality: "Egyptian",
    country: "Egypt",
    status: "Inactive",
    lastLogin: "2025-12-15T08:20:00Z",
    createdAt: "2025-07-10T11:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-010",
    fullName: "Yousef Adnan Malak",
    email: "yousef.malak@playzoon.com",
    mobile: "509998877",
    countryCode: "+966",
    roleId: "role-006",
    roleName: "Reports Analyst",
    roleColourHex: "#8B5CF6",
    nationality: "Kuwaiti",
    country: "Kuwait",
    status: "Active",
    lastLogin: undefined,
    createdAt: "2026-02-20T16:00:00Z",
    mustChangePassword: true,
  },
  {
    id: "sa-011",
    fullName: "Hassan Al-Farsi",
    email: "hassan.farsi@playzoon.com",
    mobile: "552223344",
    countryCode: "+966",
    roleId: "role-003",
    roleName: "Support Agent",
    roleColourHex: "#06B6D4",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-03-05T14:30:00Z",
    createdAt: "2026-01-20T09:00:00Z",
    mustChangePassword: false,
  },
  {
    id: "sa-012",
    fullName: "Mona Al-Qurashi",
    email: "mona.qurashi@playzoon.com",
    mobile: "505556677",
    countryCode: "+966",
    roleId: "role-001",
    roleName: "Content Manager",
    roleColourHex: "#3B82F6",
    nationality: "Saudi",
    country: "Saudi Arabia",
    status: "Active",
    lastLogin: "2026-03-08T09:15:00Z",
    createdAt: "2026-02-01T10:00:00Z",
    mustChangePassword: false,
  },
];
