import { Review, ReviewType, HideReasonCategory } from "./types";
import { subDays, subHours } from "date-fns";

const reviewers = [
  { id: "USR-001", name: "Ahmed Al-Rashid", photo: "https://i.pravatar.cc/150?u=ahmed001", email: "ahmed.rashid@example.com" },
  { id: "USR-002", name: "Sarah Mohamed", photo: "https://i.pravatar.cc/150?u=sarah002", email: "sarah.m@example.com" },
  { id: "USR-003", name: "Omar Khalid", photo: "https://i.pravatar.cc/150?u=omar003", email: "omar.k@example.com" },
  { id: "USR-004", name: "Layla Hassan", photo: "https://i.pravatar.cc/150?u=layla004", email: "layla.h@example.com" },
  { id: "USR-005", name: "Youssef Nasser", photo: "https://i.pravatar.cc/150?u=youssef005", email: "youssef.n@example.com" },
  { id: "USR-006", name: "Fatima Yusuf", photo: "https://i.pravatar.cc/150?u=fatima006", email: "fatima.y@example.com" },
  { id: "USR-007", name: "Khalid Ibrahim", photo: "https://i.pravatar.cc/150?u=khalid007", email: "khalid.i@example.com" },
  { id: "USR-008", name: "Mona Saleh", photo: "https://i.pravatar.cc/150?u=mona008", email: "mona.s@example.com" },
  { id: "USR-009", name: "Tariq Mahmoud", photo: "https://i.pravatar.cc/150?u=tariq009", email: "tariq.m@example.com" },
  { id: "USR-010", name: "Nadia Al-Farsi", photo: "https://i.pravatar.cc/150?u=nadia010", email: "nadia.f@example.com" },
];

const targets: { id: string; name: string; type: ReviewType }[] = [
  { id: "FAC-001", name: "Al-Khalij Sports Arena", type: "Facility" },
  { id: "FAC-002", name: "Doha Football Complex", type: "Facility" },
  { id: "FAC-003", name: "Pearl Sports Hub", type: "Facility" },
  { id: "TRN-001", name: "Advanced Tennis Bootcamp", type: "Training" },
  { id: "TRN-002", name: "Youth Football Academy", type: "Training" },
  { id: "TRN-003", name: "Swimming Fundamentals", type: "Training" },
  { id: "COA-001", name: "Coach Hassan Al-Sayed", type: "Coach" },
  { id: "COA-002", name: "Coach Maria Fernandez", type: "Coach" },
  { id: "COA-003", name: "Coach James Miller", type: "Coach" },
  { id: "TRN-004", name: "Ramadan Cup 2025", type: "Tournament" },
  { id: "TRN-005", name: "Youth Basketball League", type: "Tournament" },
];

const positiveComments = [
  "Absolutely fantastic experience! The facilities were pristine, staff was incredibly welcoming and professional. Will definitely be back.",
  "Great coaching session. The coach really took time to understand my level and tailored the training accordingly.",
  "Top-notch facility with excellent amenities. The courts are well-maintained and booking was seamless.",
  "Very impressed with the professionalism and quality of the training. Highly recommend to everyone.",
  "Loved every minute. The staff was helpful, the environment was clean, and the overall experience exceeded my expectations.",
  "Excellent tournament organization. Everything ran on time, referees were fair, and the atmosphere was electric.",
];

const neutralComments = [
  "Decent experience overall. The facility was okay but could use some updates to the equipment.",
  "Average coaching. The session was fine but nothing particularly stood out. Might try again.",
  "Facilities are acceptable. Parking was a bit of an issue but otherwise it was fine.",
  "It was okay. Not the best I've attended but not bad either. Probably won't go out of my way to return.",
  "The experience was average. I expected more based on the price point.",
];

const negativeComments = [
  "The worst experience I've had. Equipment was broken, staff were rude, and they refused to issue a refund.",
  "Extremely disappointed. The court was double-booked and nobody seemed to care about resolving the issue.",
  "Totally fake reviews on this profile. I've been there and it's nothing like what's advertised.",
  "Buy buy buy! Click this link for amazing deals on sports equipment!! 100% discount today only!!!",
  "Disgusting behavior from the coach. Used inappropriate language during training. Unacceptable.",
  "They stole my deposit and are now ignoring my messages. Avoid at all costs.",
  "This review is exactly the same experience as someone else posted. Nothing original here.",
];

export const MOCK_REVIEWS: Review[] = [
  // ─── Visible reviews (published, no issues) ─────────────────────────────────
  {
    id: "REV-2001",
    reviewer: reviewers[0],
    target: targets[0],
    rating: 5,
    text: positiveComments[0],
    submittedAt: subHours(new Date(), 3).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2002",
    reviewer: reviewers[1],
    target: targets[3],
    rating: 4,
    text: positiveComments[1],
    submittedAt: subHours(new Date(), 7).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2008",
    reviewer: reviewers[7],
    target: targets[2],
    rating: 5,
    text: positiveComments[3],
    submittedAt: subDays(new Date(), 3).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2009",
    reviewer: reviewers[8],
    target: targets[5],
    rating: 4,
    text: positiveComments[4],
    submittedAt: subDays(new Date(), 4).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2010",
    reviewer: reviewers[9],
    target: targets[8],
    rating: 4,
    text: positiveComments[5],
    submittedAt: subDays(new Date(), 5).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2011",
    reviewer: reviewers[0],
    target: targets[10],
    rating: 3,
    text: neutralComments[1],
    submittedAt: subDays(new Date(), 6).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2012",
    reviewer: reviewers[1],
    target: targets[0],
    rating: 5,
    text: positiveComments[0],
    submittedAt: subDays(new Date(), 7).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2013",
    reviewer: reviewers[2],
    target: targets[6],
    rating: 4,
    text: neutralComments[2],
    submittedAt: subDays(new Date(), 8).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2014",
    reviewer: reviewers[3],
    target: targets[3],
    rating: 2,
    text: neutralComments[3],
    submittedAt: subDays(new Date(), 9).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2015",
    reviewer: reviewers[4],
    target: targets[7],
    rating: 5,
    text: positiveComments[1],
    submittedAt: subDays(new Date(), 10).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2016",
    reviewer: reviewers[5],
    target: targets[1],
    rating: 3,
    text: neutralComments[4],
    submittedAt: subDays(new Date(), 11).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2017",
    reviewer: reviewers[6],
    target: targets[9],
    rating: 4,
    text: positiveComments[3],
    submittedAt: subDays(new Date(), 12).toISOString(),
    status: "Visible",
  },
  {
    id: "REV-2018",
    reviewer: reviewers[7],
    target: targets[4],
    rating: 5,
    text: positiveComments[5],
    submittedAt: subDays(new Date(), 14).toISOString(),
    status: "Visible",
  },

  // ─── Flagged reviews (provider-flagged, awaiting admin review) ───────────────
  {
    id: "REV-2003",
    reviewer: reviewers[2],
    target: targets[6],
    rating: 1,
    text: negativeComments[0],
    submittedAt: subHours(new Date(), 12).toISOString(),
    status: "Flagged",
    flaggedByProvider: "Coach Hassan Al-Sayed",
    flaggedReason: "Review contains offensive language and personal attacks",
  },
  {
    id: "REV-2004",
    reviewer: reviewers[3],
    target: targets[9],
    rating: 1,
    text: negativeComments[2],
    submittedAt: subDays(new Date(), 1).toISOString(),
    status: "Flagged",
    flaggedByProvider: "Ramadan Cup 2025 Organizer",
    flaggedReason: "Review contains false and misleading information",
  },
  {
    id: "REV-2005",
    reviewer: reviewers[4],
    target: targets[1],
    rating: 2,
    text: negativeComments[1],
    submittedAt: subDays(new Date(), 1).toISOString(),
    status: "Flagged",
    flaggedByProvider: "Doha Football Complex",
    flaggedReason: "Double booking issue was resolved but review remains unfair",
  },
  {
    id: "REV-2006",
    reviewer: reviewers[5],
    target: targets[7],
    rating: 1,
    text: negativeComments[4],
    submittedAt: subDays(new Date(), 2).toISOString(),
    status: "Flagged",
    flaggedByProvider: "Coach Maria Fernandez",
    flaggedReason: "Allegations are false and defamatory",
  },
  {
    id: "REV-2007",
    reviewer: reviewers[6],
    target: targets[4],
    rating: 1,
    text: negativeComments[3],
    submittedAt: subDays(new Date(), 2).toISOString(),
    status: "Flagged",
    flaggedByProvider: "Youth Football Academy",
    flaggedReason: "This is spam, not a genuine review",
  },

  // ─── Hidden reviews (admin has hidden — BR-005: USR-003 has 3+ hidden in 30 days)
  {
    id: "REV-2019",
    reviewer: reviewers[2], // USR-003 – hidden #1
    target: targets[0],
    rating: 1,
    text: negativeComments[3], // spam
    submittedAt: subDays(new Date(), 5).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Spam",
    hiddenAt: subDays(new Date(), 4).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2020",
    reviewer: reviewers[2], // USR-003 – hidden #2
    target: targets[6],
    rating: 1,
    text: negativeComments[4],
    submittedAt: subDays(new Date(), 10).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Inappropriate Content",
    hiddenAt: subDays(new Date(), 9).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2021",
    reviewer: reviewers[2], // USR-003 – hidden #3
    target: targets[3],
    rating: 1,
    text: negativeComments[2],
    submittedAt: subDays(new Date(), 15).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Fake Review",
    hiddenAt: subDays(new Date(), 14).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2022",
    reviewer: reviewers[8], // USR-009 – hidden #1
    target: targets[2],
    rating: 1,
    text: negativeComments[5],
    submittedAt: subDays(new Date(), 8).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Fake Review",
    hiddenAt: subDays(new Date(), 7).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2023",
    reviewer: reviewers[8], // USR-009 – hidden #2
    target: targets[10],
    rating: 1,
    text: negativeComments[3],
    submittedAt: subDays(new Date(), 12).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Spam",
    hiddenAt: subDays(new Date(), 11).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2024",
    reviewer: reviewers[8], // USR-009 – hidden #3
    target: targets[4],
    rating: 1,
    text: negativeComments[6],
    submittedAt: subDays(new Date(), 18).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Policy Violation",
    hiddenAt: subDays(new Date(), 17).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2025",
    reviewer: reviewers[0],
    target: targets[1],
    rating: 1,
    text: negativeComments[1],
    submittedAt: subDays(new Date(), 20).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Inappropriate Content",
    hiddenAt: subDays(new Date(), 19).toISOString(),
    hiddenBy: "Super Admin",
  },
  {
    id: "REV-2026",
    reviewer: reviewers[4],
    target: targets[7],
    rating: 2,
    text: negativeComments[0],
    submittedAt: subDays(new Date(), 22).toISOString(),
    status: "Hidden",
    hideReasonCategory: "Other",
    hideAdditionalNotes: "Review violated platform community standards.",
    hiddenAt: subDays(new Date(), 21).toISOString(),
    hiddenBy: "Super Admin",
  },
];
