// ─── Cancellation Policy Management — Mock Data ───────────────────────

import { CancellationPolicy } from "./types";

export const MOCK_POLICIES: CancellationPolicy[] = [
  // ── 1. Standard Facility Policy (Active, Default) ──────────────────────
  {
    id: "CP-001",
    name: "Standard Facility Policy",
    applicableTo: ["Facility"],
    tiers: [
      {
        id: "T-001-1",
        comparison: "More than",
        lowerValue: 48,
        lowerUnit: "hours",
        refundPercentage: 100,
        platformFeeRefundable: false,
      },
      {
        id: "T-001-2",
        comparison: "Between",
        lowerValue: 24,
        lowerUnit: "hours",
        upperValue: 48,
        upperUnit: "hours",
        refundPercentage: 50,
        platformFeeRefundable: false,
      },
      {
        id: "T-001-3",
        comparison: "Less than",
        lowerValue: 24,
        lowerUnit: "hours",
        refundPercentage: 0,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 0,
    cancellationFeeCurrency: "AED",
    isDefault: true,
    assignedProviders: 12,
    status: "Active",
    createdAt: "2026-01-10T09:00:00Z",
    updatedAt: "2026-01-10T09:00:00Z",
    createdBy: "Sarah Al-Mansoori",
    activatedAt: "2026-01-10T09:00:00Z",
  },

  // ── 2. Premium Training Refund (Active) ─────────────────────────────────
  {
    id: "CP-002",
    name: "Premium Training Refund",
    applicableTo: ["Training"],
    tiers: [
      {
        id: "T-002-1",
        comparison: "More than",
        lowerValue: 3,
        lowerUnit: "days",
        refundPercentage: 100,
        platformFeeRefundable: true,
      },
      {
        id: "T-002-2",
        comparison: "Between",
        lowerValue: 24,
        lowerUnit: "hours",
        upperValue: 3,
        upperUnit: "days",
        refundPercentage: 75,
        platformFeeRefundable: false,
      },
      {
        id: "T-002-3",
        comparison: "Less than",
        lowerValue: 24,
        lowerUnit: "hours",
        refundPercentage: 0,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 25,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 8,
    status: "Active",
    createdAt: "2026-01-12T10:00:00Z",
    updatedAt: "2026-01-12T10:00:00Z",
    createdBy: "Omar Hassan",
    activatedAt: "2026-01-12T10:00:00Z",
  },

  // ── 3. Coach Session Policy (Active) ────────────────────────────────────
  {
    id: "CP-003",
    name: "Coach Session Policy",
    applicableTo: ["Coach"],
    tiers: [
      {
        id: "T-003-1",
        comparison: "More than",
        lowerValue: 48,
        lowerUnit: "hours",
        refundPercentage: 100,
        platformFeeRefundable: true,
      },
      {
        id: "T-003-2",
        comparison: "Less than",
        lowerValue: 48,
        lowerUnit: "hours",
        refundPercentage: 25,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 15,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 5,
    status: "Active",
    createdAt: "2026-01-15T08:30:00Z",
    updatedAt: "2026-01-15T08:30:00Z",
    createdBy: "Sarah Al-Mansoori",
    activatedAt: "2026-01-15T08:30:00Z",
  },

  // ── 4. Strict No-Refund — Legacy (Inactive, was assigned) ──────────────
  {
    id: "CP-004",
    name: "Strict No-Refund (Legacy)",
    applicableTo: ["Facility", "Training"],
    tiers: [
      {
        id: "T-004-1",
        comparison: "Less than",
        lowerValue: 72,
        lowerUnit: "hours",
        refundPercentage: 0,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 50,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 3,
    status: "Inactive",
    createdAt: "2025-10-01T09:00:00Z",
    updatedAt: "2026-01-10T09:01:00Z",
    createdBy: "Omar Hassan",
  },

  // ── 5. All-Types Launch Policy (Inactive, no longer assigned) ──────────
  {
    id: "CP-005",
    name: "All Types — Launch Policy",
    applicableTo: ["Facility", "Training", "Coach"],
    tiers: [
      {
        id: "T-005-1",
        comparison: "More than",
        lowerValue: 3,
        lowerUnit: "days",
        refundPercentage: 100,
        platformFeeRefundable: true,
      },
      {
        id: "T-005-2",
        comparison: "Between",
        lowerValue: 24,
        lowerUnit: "hours",
        upperValue: 3,
        upperUnit: "days",
        refundPercentage: 50,
        platformFeeRefundable: false,
      },
      {
        id: "T-005-3",
        comparison: "Less than",
        lowerValue: 24,
        lowerUnit: "hours",
        refundPercentage: 0,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 0,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 0,
    status: "Inactive",
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2026-01-15T08:31:00Z",
    createdBy: "Omar Hassan",
  },

  // ── 6. Facility Weekend Events — Draft ──────────────────────────────────
  {
    id: "CP-006",
    name: "Facility — Weekend Events Draft",
    applicableTo: ["Facility"],
    tiers: [
      {
        id: "T-006-1",
        comparison: "More than",
        lowerValue: 24,
        lowerUnit: "hours",
        refundPercentage: 100,
        platformFeeRefundable: false,
      },
      {
        id: "T-006-2",
        comparison: "Less than",
        lowerValue: 24,
        lowerUnit: "hours",
        refundPercentage: 25,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 10,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 0,
    status: "Draft",
    createdAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-02-15T11:00:00Z",
    createdBy: "Sarah Al-Mansoori",
  },

  // ── 7. Flexible Coach Policy (Draft) ────────────────────────────────────
  {
    id: "CP-007",
    name: "Flexible Coach Policy",
    applicableTo: ["Coach"],
    tiers: [
      {
        id: "T-007-1",
        comparison: "More than",
        lowerValue: 12,
        lowerUnit: "hours",
        refundPercentage: 100,
        platformFeeRefundable: true,
      },
      {
        id: "T-007-2",
        comparison: "Between",
        lowerValue: 4,
        lowerUnit: "hours",
        upperValue: 12,
        upperUnit: "hours",
        refundPercentage: 50,
        platformFeeRefundable: false,
      },
      {
        id: "T-007-3",
        comparison: "Less than",
        lowerValue: 4,
        lowerUnit: "hours",
        refundPercentage: 10,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 0,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 0,
    status: "Draft",
    createdAt: "2026-02-20T14:00:00Z",
    updatedAt: "2026-02-20T14:00:00Z",
    createdBy: "Omar Hassan",
  },

  // ── 8. Training Weekend Intensive (Active, assigned) ────────────────────
  {
    id: "CP-008",
    name: "Training Weekend Intensive",
    applicableTo: ["Training"],
    tiers: [
      {
        id: "T-008-1",
        comparison: "More than",
        lowerValue: 2,
        lowerUnit: "days",
        refundPercentage: 90,
        platformFeeRefundable: true,
      },
      {
        id: "T-008-2",
        comparison: "Less than",
        lowerValue: 2,
        lowerUnit: "days",
        refundPercentage: 0,
        platformFeeRefundable: false,
      },
    ],
    cancellationFee: 35,
    cancellationFeeCurrency: "AED",
    isDefault: false,
    assignedProviders: 4,
    status: "Active",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-10T12:00:00Z",
    createdBy: "Sarah Al-Mansoori",
    activatedAt: "2026-02-10T12:00:00Z",
  },
];
